apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9600"
    prometheus.io/scrape: "true"
  labels:
    app: eric-enm-ondemand-pods-manager
    app.kubernetes.io/name: eric-enm-ondemand-pods-manager
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: eric-enm-ondemand-pods-manager
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: metrics
      port: 9600
      protocol: TCP
      targetPort: 9600
  selector:
    app.kubernetes.io/name: eric-enm-ondemand-pods-manager
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9600"
    prometheus.io/scheme: http
  labels:
    app: eric-enm-ondemand-pods-manager
    app.kubernetes.io/name: eric-enm-ondemand-pods-manager
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: eric-enm-ondemand-pods-manager
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: eric-enm-ondemand-pods-manager
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8095"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/name: eric-enm-ondemand-pods-manager
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - eric-enm-ondemand-pods-manager
              topologyKey: "kubernetes.io/hostname"
      containers:
        - env:
            - name: TZ
            - name: JBOSS_LOG_LEVEL
            - name: SERVICE_NAME
              value: eric-enm-ondemand-pods-manager
          image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/eric-odp-k8s-operator:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: eric-enm-ondemand-pods-manager
          resources: {}
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsGroup: 5004
            runAsNonRoot: true
            runAsUser: 1000809999
          ports:
            - containerPort: 8095
              name: metrics
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /logs
              name: logs
              readOnly: false
            - mountPath: /ericsson/tor/data
              name: data
        - args:
            - -redirect=all
            - -size=2
            - -rotate=5
            - -logfile=/logs/logshipper.log
            - --
            - /opt/fluent-bit/scripts/init.sh
            - --config=/etc/fluent-bit/fluent-bit.conf
          command:
            - stdout-redirect
          env:
            - name: TLS_ENABLED
              value: "false"
            - name: SHUTDOWN_DELAY
              value: "10"
            - name: SERVICE_ID
              value: eric-enm-ondemand-pods-manager
            - name: RUN_AND_EXIT
              value: "false"
            - name: CONTAINER_NAME
              value: logshipper
            - name: LOG_PATH
              value: /logs
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LS_SIDECAR_CERT_FILE
              value: clicert.pem
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LS_SIDECAR_KEY_FILE
              value: cliprivkey.pem
            - name: LOG_LEVEL
              value: info
            - name: LS_SIDECAR_CA_CERT_FILE
              value: ca.crt
            - name: CLIENT_CERT_PATH
              value: /run/secrets/eric-enm-ondemand-pods-manager-log-shipper-sidecar-lt-http-client-cert
          envFrom:
            - configMapRef:
                name: eric-enm-odp-logshipper-envvar-cfg
          image: ieatjfrepo1.athtem.eei.ericsson.se/hub/proj-adp-log-released/eric-log-shipper-sidecar:16.0.1-72
          imagePullPolicy: IfNotPresent
          name: logshipper
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 50Mi
          volumeMounts:
            - mountPath: /etc/fluent-bit/
              name: fluentbit-config
              readOnly: true
            - mountPath: /logs
              name: logs
              readOnly: false
            - mountPath: /gp
              name: gp
            - mountPath: /var/lib/eric-odp
              name: var-lib-eric-odp
      initContainers:
        - args:
            - |
              /usr/local/bin/get_ldap_properties.sh
          command:
            - /bin/bash
            - -c
          image: armdocker.rnd.ericsson.se/proj_oss_releases/enm/eric-odp-idm-connectors-init:zahsarp-test
          imagePullPolicy: Always
          name: ldap-init
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /ericsson/tor/data
              name: data
            - mountPath: /gp
              name: gp
            - mountPath: /var/lib/eric-odp
              name: var-lib-eric-odp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: eric-enm-ondemand-pods-manager
      serviceAccountName: eric-enm-ondemand-pods-manager
      terminationGracePeriodSeconds: 60
      volumes:
        - configMap:
            defaultMode: 420
            name: gpodpmanager
          name: gp
        - emptyDir:
            sizeLimit: 5Mi
          name: var-lib-eric-odp
        - configMap:
            defaultMode: 420
            items:
              - key: filters.conf
                path: filters.conf
              - key: fluent-bit.conf
                path: fluent-bit.conf
              - key: inputs.conf
                path: inputs.conf
              - key: outputs.conf
                path: outputs.conf
              - key: parsers.conf
                path: parsers.conf
            name: eric-enm-odp-logshipper-cfg
            optional: false
          name: fluentbit-config
        - emptyDir:
            sizeLimit: 100Mi
          name: logs
        - name: data
          persistentVolumeClaim:
            claimName: eric-enm-rwxpvc-data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
  labels:
    app: eric-enm-ondemand-pods-manager
    app.kubernetes.io/name: eric-enm-ondemand-pods-manager
    app.kubernetes.io/version: ondemand-pods-manager-1.0.0
  name: eric-enm-ondemand-pods-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  labels:
  name: eric-enm-ondemand-jobs-role
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - update
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
  labels:
  name: eric-enm-ondemand-pods-manager-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eric-enm-ondemand-jobs-role
subjects:
  - kind: ServiceAccount
    name: eric-enm-ondemand-pods-manager
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-enm-ondemand-pods-manager-envvar-cfg
data:
  TZ: Europe/Dublin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-enm-ondemand-pods-manager-logshipper-cfg
data:
  fluent-bit.conf: |
    @INCLUDE /etc/fluent-bit/inputs.conf
    @INCLUDE /etc/fluent-bit/outputs.conf
    @INCLUDE /etc/fluent-bit/filters.conf

    [SERVICE]
        flush           3
        grace           10
        log_level       info
        parsers_file    /etc/fluent-bit/parsers.conf
        http_server     on
        http_listen     localhost
        http_port       2020
        storage.metrics on

  parsers.conf: |
    [PARSER]
        name   json
        format json
  inputs.conf: |
    [INPUT]
        name              tail
        tag               event.fluent-bit
        alias             log_shipper
        buffer_chunk_size 32k
        buffer_max_size   32k
        path              /logs/logshipper.log
        path_key          filename
        read_from_head    true
        refresh_interval  5
        rotate_wait       10
        skip_empty_lines  off
        skip_long_lines   off
        key               message
        db                /logs/logshipper.db
        db.sync           normal
        db.locking        true
        db.journal_mode   off
        parser            json
        mem_buf_limit     1MB
    [INPUT]
        name              tail
        tag               event.file0
        alias             file0
        buffer_chunk_size 32k
        buffer_max_size   32k
        read_from_head    true
        refresh_interval  5
        rotate_wait       10
        skip_empty_lines  off
        skip_long_lines   off
        key               message
        db                /logs/file0.db
        db.sync           normal
        db.locking        true
        db.journal_mode   off
        path              /logs/application.log*
        path_key          filename
        exclude_path      /logs/logshipper.log
        mem_buf_limit     1MB
  filters.conf: |
    [FILTER]
        name     parser
        match    event.file0
        parser   json
        key_name message
        reserve_data true
    [FILTER]
        name          nest
        match         event.*
        operation     lift
        nested_under  extra_data
        add_prefix    extradata.
    [FILTER]
        name          nest
        match         event.*
        operation     nest
        wildcard      filename*
        nest_under    fluentbit
    [FILTER]
        name          nest
        match         event.*
        operation     nest
        wildcard      fluentbit*
        wildcard      extradata.*
        nest_under    extra_data
        remove_prefix extradata.
    [FILTER]
        name  modify
        match event.fluent-bit
        add   metadata.container_name ${CONTAINER_NAME}
    [FILTER]
        name          modify
        match         event.*
        condition     key_does_not_exist version
        add           version            1.2.0
    [FILTER]
        name          modify
        match         event.*
        condition     key_does_not_exist service_id
        add           service_id         eric-enm-ondemand-pods-manager
    [FILTER]
        name          modify
        match         event.*
        condition     key_does_not_exist severity
        add           severity           info
    [FILTER]
        name  modify
        match event.*
        add   metadata.namespace ${NAMESPACE}
        add   metadata.node_name ${NODE_NAME}
        add   metadata.pod_name  ${POD_NAME}
        add   metadata.pod_uid   ${POD_UID}
    [FILTER]
        name          nest
        match         event.*
        operation     lift
        nested_under  metadata
        add_prefix    metadata.
    [FILTER]
        name          nest
        match         event.*
        operation     nest
        wildcard      metadata.*
        nest_under    metadata
        remove_prefix metadata.
  outputs.conf: |
    [OUTPUT]
        name                 http
        match                event.*
        alias                log_transformer
        json_date_key        false
        host                 eric-log-transformer
        port                 9080
        retry_limit          false
        log_response_payload false
        format               json


