apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.role.name }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "update", "watch", "list"]
  - apiGroups: [""]
    resources:  ["pods"]
    verbs: ["watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rolebinding.name }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.role.name }}
  apiGroup:  rbac.authorization.k8s.io