{{ define "eric-odp-ssh-proxy.service.tpl" }}
apiVersion: v1
kind: Service
metadata:
{{ include "eric-odp-ssh-proxy.metadata" . | indent 2 }}
spec:
  type: LoadBalancer
  ipFamilies: ["IPv4"]
  ipFamilyPolicy: SingleStack
  loadBalancerIP: {{ .Values.ssh_broker_service.loadBalancerIPv4 }}
  ports:
{{ tpl (.Files.Get "appconfig/sshProxy/servicePorts.yaml") . | indent 4 }}
  selector:
    #headless selector
    name: {{ .Values.ssh_broker_service.name }}
{{ end }}
{{ define "eric-odp-ssh-proxy.service" }}
{{ template "eric-odp-ssh-proxy.util.merge" (append . "eric-odp-ssh-proxy.service.tpl") }}
{{ end }}
